In [27]:
import torch
import pandas as pd
import numpy as np

In [28]:
# vectors
temp = torch.FloatTensor([[4,5,3,2.2],[3,7,8,3]])
print(temp)
print(temp.size())
print(temp.shape)
print(temp[1])
print(temp[1,3],'\n')

temp2 = torch.rand(3,5)
print(temp2)
print(temp2.size())
print(temp2.shape)
print(temp2[1])
print(temp2[1,1])

tensor([[4.0000, 5.0000, 3.0000, 2.2000],
        [3.0000, 7.0000, 8.0000, 3.0000]])
torch.Size([2, 4])
torch.Size([2, 4])
tensor([3., 7., 8., 3.])
tensor(3.) 

tensor([[0.6377, 0.7162, 0.0659, 0.2725, 0.3670],
        [0.5839, 0.6603, 0.6496, 0.6779, 0.0826],
        [0.4570, 0.4594, 0.4333, 0.5891, 0.6603]])
torch.Size([3, 5])
torch.Size([3, 5])
tensor([0.5839, 0.6603, 0.6496, 0.6779, 0.0826])
tensor(0.6603)


In [29]:
# scalars
x = torch.rand(10)
print(x)
print(x.size())
print(x.shape)

tensor([0.8268, 0.3019, 0.9228, 0.6079, 0.2745, 0.6473, 0.6349, 0.9108, 0.3204,
        0.4035])
torch.Size([10])
torch.Size([10])


In [37]:
from sklearn.datasets import fetch_california_housing
c_housing = fetch_california_housing()

In [40]:
# matrices
c_housing_tensor = torch.from_numpy(c_housing.data)
c_housing_tensor

tensor([[   8.3252,   41.0000,    6.9841,  ...,    2.5556,   37.8800,
         -122.2300],
        [   8.3014,   21.0000,    6.2381,  ...,    2.1098,   37.8600,
         -122.2200],
        [   7.2574,   52.0000,    8.2881,  ...,    2.8023,   37.8500,
         -122.2400],
        ...,
        [   1.7000,   17.0000,    5.2055,  ...,    2.3256,   39.4300,
         -121.2200],
        [   1.8672,   18.0000,    5.3295,  ...,    2.1232,   39.4300,
         -121.3200],
        [   2.3886,   16.0000,    5.2547,  ...,    2.6170,   39.3700,
         -121.2400]], dtype=torch.float64)