In [ ]:
import torch

## Creating tensors

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.0542, 0.3341, 0.5232],
        [0.4710, 0.8696, 0.5649]])

In [ ]:
b = torch.randint(size=(2,2), low=2, high=10)
b

tensor([[2, 7],
        [3, 5]])

In [ ]:
# tensor of 1s
ones = torch.ones(2,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# tensor of zeros
zeros = torch.zeros(4,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# seed for random , makes same values again
torch.manual_seed(32)
b = torch.rand(2,3)
display(b)
display(b)
display(b)

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793]])

In [ ]:
# tensor with custom values
t = torch.tensor([[3,6,3],[1,6,2]])
t

tensor([[3, 6, 3],
        [1, 6, 2]])

In [ ]:
# a tensor of values from specific range
torch.arange(0, 100, 3)

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# linear space, one-dimensional tensor containing a specified number of evenly spaced values
torch.linspace(2, 10, 10)

tensor([ 2.0000,  2.8889,  3.7778,  4.6667,  5.5556,  6.4444,  7.3333,  8.2222,
         9.1111, 10.0000])

In [ ]:
# identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# a matrix of specific num
torch.full((3,5), 6)

tensor([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])

## Shapes

In [ ]:
torch.manual_seed(32)
t = torch.rand(size=(4,4), dtype=torch.float32)
t

tensor([[0.8757, 0.2721, 0.4141, 0.7857],
        [0.1130, 0.5793, 0.6481, 0.0229],
        [0.5874, 0.3254, 0.9485, 0.5219],
        [0.8782, 0.7254, 0.6929, 0.0259]])

In [ ]:
t.shape

torch.Size([4, 4])

In [ ]:
# create empty tensor of same dim as t
torch.empty_like(t)

tensor([[-8.1946e-20,  4.4840e-41, -8.1946e-20,  4.4840e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
# ones like t
torch.ones_like(t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# zeros like t
torch.zeros_like(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.rand_like(t) # only works for float type

tensor([[0.8867, 0.2971, 0.7828, 0.5105],
        [0.8187, 0.4370, 0.1878, 0.8781],
        [0.1925, 0.6161, 0.7849, 0.1381],
        [0.0455, 0.7794, 0.0059, 0.1268]])

## Data Types

In [ ]:
torch.manual_seed(32)
t = torch.randint(size=(2,2), low=4, high=10)
t

tensor([[5, 9],
        [7, 4]])

In [ ]:
t = t.to(torch.float32)
t

tensor([[5., 9.],
        [7., 4.]])

In [ ]:
t = t.to(torch.bool)
t

tensor([[True, True],
        [True, True]])

## Maths

### Scalar and Matrix

In [ ]:
x = torch.randint(size=(4,4), low=3, high=35)
x

tensor([[ 4,  5,  6, 27],
        [13, 21, 13, 23],
        [21,  7,  7, 28],
        [ 8, 28,  9, 16]])

In [ ]:
x + 2

tensor([[ 6,  7,  8, 29],
        [15, 23, 15, 25],
        [23,  9,  9, 30],
        [10, 30, 11, 18]])

In [ ]:
x * 4

tensor([[ 16,  20,  24, 108],
        [ 52,  84,  52,  92],
        [ 84,  28,  28, 112],
        [ 32, 112,  36,  64]])

In [ ]:
x ** 2

tensor([[ 16,  25,  36, 729],
        [169, 441, 169, 529],
        [441,  49,  49, 784],
        [ 64, 784,  81, 256]])

In [ ]:
x / 9

tensor([[0.4444, 0.5556, 0.6667, 3.0000],
        [1.4444, 2.3333, 1.4444, 2.5556],
        [2.3333, 0.7778, 0.7778, 3.1111],
        [0.8889, 3.1111, 1.0000, 1.7778]])

In [ ]:
x % 3

tensor([[1, 2, 0, 0],
        [1, 0, 1, 2],
        [0, 1, 1, 1],
        [2, 1, 0, 1]])

In [ ]:
x // 5

tensor([[0, 1, 1, 5],
        [2, 4, 2, 4],
        [4, 1, 1, 5],
        [1, 5, 1, 3]])

### Matrix to Matrix

In [ ]:
a = torch.randint(size=(2,2), low=3, high=25)
b = torch.randint(size=(2,2), low=3, high=25)
display(a)
display(b)

tensor([[13, 18],
        [ 5, 10]])

tensor([[11,  9],
        [15, 17]])

In [ ]:
a + b

tensor([[24, 27],
        [20, 27]])

In [ ]:
a - b

tensor([[  2,   9],
        [-10,  -7]])

In [ ]:
a * b

tensor([[143, 162],
        [ 75, 170]])

In [ ]:
a / b

tensor([[1.1818, 2.0000],
        [0.3333, 0.5882]])

In [ ]:
a % b

tensor([[ 2,  0],
        [ 5, 10]])

In [ ]:
a ** b

tensor([[     1792160394037,       198359290368],
        [       30517578125, 100000000000000000]])

### Built in

In [ ]:
a = torch.tensor([[3,2,1], [6.4, 3.2,6]])
a

tensor([[3.0000, 2.0000, 1.0000],
        [6.4000, 3.2000, 6.0000]])

In [ ]:
# absolute values
a.abs()

tensor([[3.0000, 2.0000, 1.0000],
        [6.4000, 3.2000, 6.0000]])

In [ ]:
# neg values
a.neg()

tensor([[-3.0000, -2.0000, -1.0000],
        [-6.4000, -3.2000, -6.0000]])

In [ ]:
# round elements
a.round()

tensor([[3., 2., 1.],
        [6., 3., 6.]])

In [ ]:
a.ceil()

tensor([[3., 2., 1.],
        [7., 4., 6.]])

In [ ]:
a.floor()

tensor([[3., 2., 1.],
        [6., 3., 6.]])

In [ ]:
a.clamp(min=2, max=5)

tensor([[3.0000, 2.0000, 2.0000],
        [5.0000, 3.2000, 5.0000]])