In [41]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

## Manual

In [38]:
# coffee example
# data -> temp, time
x = np.array([[200.0, 20.0]])
print(x)
# layers
layer_1 = Dense(units=3, activation='sigmoid')
a1 = layer_1(x)
print(a1)
layer_2 = Dense(units=1, activation='sigmoid')
a2 = layer_2(a1)
print(a2)
if a2 >= 0.5:
  print('good coffee')
else:
  print('bad coffee')

[[200.  20.]]
tf.Tensor([[9.485656e-26 0.000000e+00 0.000000e+00]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)
good coffee


In [39]:
# coffee example
# data -> temp, time
x = np.array([[200.0, 20.0]])
print(x)
# layers
layer_1 = Dense(units=3, activation='relu')
a1 = layer_1(x)
print(a1)
layer_2 = Dense(units=1, activation='relu')
a2 = layer_2(a1)
print(a2)
if a2 >= 0.5:
  print('good coffee')
else:
  print('bad coffee')

[[200.  20.]]
tf.Tensor([[ 0.        0.       11.662459]], shape=(1, 3), dtype=float32)
tf.Tensor([[3.8663354]], shape=(1, 1), dtype=float32)
good coffee


## Sequential model

In [55]:
# data
x = np.array([[200, 17],
              [120, 5],
              [425, 20],
              [212, 18]])
y = np.array([1,0,0,1])

# model
model = Sequential([
    Dense(units=3, activation='sigmoid'),
    Dense(units=1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy')
model.fit(x, y)
new_data = np.array([[200,30]])

pred = model.predict(new_data)
print(pred)
if pred >= 0.5:
  print('good coffee')
else:
  print('bad coffee')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 940ms/step - loss: 0.7421


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[0.5791244]]
good coffee


In [56]:
# data
x = np.array([[200, 17],
              [120, 5],
              [425, 20],
              [212, 18]])
y = np.array([1,0,0,1])

# model
model = Sequential([
    Dense(units=3, activation='relu'),
    Dense(units=1, activation='relu')
])
model.compile(loss='binary_crossentropy')
model.fit(x, y)
new_data = np.array([[200,30]])

pred = model.predict(new_data)
print(pred)
if pred >= 0.5:
  print('good coffee')
else:
  print('bad coffee')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 544ms/step - loss: 8.0590


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[0.]]
bad coffee
