In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Data: x, y

In [6]:
# data
x = np.array([[185.32,  12.69],
 [259.92,  11.87],
 [231.01,  14.41],
 [175.37,  11.72],
 [187.12,  14.13],
 [225.91,  12.1 ],
 [208.41,  14.18],
 [207.08,  14.03],
 [280.6 ,  14.23],
 [202.87,  12.25],
 [196.7 ,  13.54],
 [270.31,  14.6 ],
 [192.95,  15.2 ],
 [213.57,  14.28],
 [164.47,  11.92],
 [177.26,  15.04],
 [241.77,  14.9 ],
 [237.  ,  13.13],
 [219.74,  13.87],
 [266.39,  13.25],
 [270.45,  13.95],
 [261.96,  13.49],
 [243.49,  12.86],
 [220.58,  12.36],
 [163.59,  11.65],
 [244.76,  13.33],
 [271.19,  14.84],
 [201.99,  15.39],
 [229.93,  14.56],
 [204.97,  12.28],
 [173.19,  12.22],
 [231.51,  11.95],
 [152.69,  14.83],
 [163.42,  13.3 ],
 [215.95,  13.98],
 [218.04,  15.25],
 [251.3 ,  13.8 ],
 [233.33,  13.53],
 [280.24,  12.41],
 [243.02,  13.72],
 [155.67,  12.68],
 [275.17,  14.64],
 [151.73,  12.69],
 [151.32,  14.81],
 [164.9 ,  11.73],
 [282.55,  13.28],
 [192.98,  11.7 ],
 [202.6 ,  12.96],
 [220.67,  11.53],
 [169.97,  12.34],
 [209.47,  12.71],
 [232.8 ,  12.64],
 [272.8 ,  15.35],
 [158.02,  12.34],
 [226.01,  14.58],
 [158.64,  12.24],
 [211.66,  14.17],
 [271.95,  14.97],
 [257.16,  11.71],
 [281.85,  13.96],
 [161.63,  12.52],
 [233.8 ,  13.04],
 [210.29,  14.72],
 [261.24,  13.69],
 [256.98,  13.12],
 [281.56,  13.92],
 [280.64,  11.68],
 [269.16,  13.74],
 [246.34,  12.27],
 [224.07,  12.66],
 [164.24,  11.51],
 [272.42,  14.18],
 [177.68,  12.53],
 [212.86,  14.77],
 [165.88,  15.37],
 [277.43,  12.48],
 [236.51,  12.94],
 [244.14,  11.85],
 [213.45,  13.85],
 [234.57,  14.27],
 [270.34,  12.47],
 [170.68,  13.06],
 [226.79,  15.34],
 [245.92,  14.45],
 [281.32,  12.57],
 [185.03,  13.19],
 [189.88,  14.1 ],
 [278.48,  12.11],
 [219.92,  14.21],
 [216.58,  15.15],
 [249.48,  15.03],
 [165.09,  12.28],
 [158.87,  14.82],
 [279.98,  11.56],
 [256.55,  14.41],
 [272.61,  12.58],
 [246.49,  12.45],
 [160.26,  14.48],
 [155.7 ,  14.3 ],
 [188.27,  13.45],
 [270.36,  12.47],
 [213.22,  12.92],
 [175.7 ,  13.39],
 [174.52,  14.7 ],
 [233.  ,  12.63],
 [281.37,  12.88],
 [240.62,  14.43],
 [185.81,  11.55],
 [270.5 ,  15.33],
 [172.98,  12.11],
 [208.41,  13.89],
 [283.51,  15.35],
 [283.36,  12.48],
 [230.85,  13.24],
 [181.24,  11.76],
 [172.78,  12.93],
 [161.88,  12.1 ],
 [156.03,  13.99],
 [216.52,  12.47],
 [221.06,  13.2 ],
 [238.99,  15.23],
 [197.69,  14.08],
 [179.55,  15.26],
 [233.39,  12.13],
 [184.7 ,  12.14],
 [174.18,  12.73],
 [261.11,  13.33],
 [187.42,  13.18],
 [186.1 ,  14.43],
 [157.94,  12.66],
 [193.64,  12.23],
 [249.65,  12.22],
 [190.56,  11.73],
 [252.  ,  12.96],
 [238.55,  12.37],
 [152.94,  12.79],
 [255.17,  14.85],
 [197.09,  14.89],
 [156.8 ,  13.59],
 [184.75,  13.26],
 [179.92,  15.07],
 [190.79,  15.28],
 [164.73,  13.22],
 [209.87,  14.34],
 [196.58,  13.47],
 [159.51,  12.74],
 [247.87,  11.92],
 [212.44,  12.45],
 [172.34,  11.99],
 [259.87,  14.25],
 [201.23,  13.07],
 [248.34,  13.92],
 [273.66,  15.18],
 [215.09,  14.14],
 [223.53,  12.74],
 [211.22,  14.38],
 [224.61,  14.03],
 [215.75,  15.31],
 [254.82,  12.02],
 [259.9 ,  15.17],
 [260.25,  12.87],
 [199.67,  12.47],
 [157.52,  13.39],
 [264.81,  14.58],
 [239.4 ,  14.89],
 [238.98,  12.39],
 [258.43,  12.97],
 [270.16,  12.81],
 [162.41,  14.42],
 [164.53,  14.98],
 [205.61,  14.62],
 [157.1 ,  13.68],
 [241.38,  12.02],
 [232.13,  12.07],
 [191.04,  12.96],
 [233.64,  12.02],
 [174.95,  14.63],
 [246.64,  13.32],
 [188.07,  14.27],
 [213.16,  12.75],
 [268.08,  12.31],
 [258.58,  13.97],
 [237.21,  14.23],
 [251.02,  15.02],
 [274.28,  12.52],
 [172.12,  15.09],
 [177.52,  12.39],
 [258.71,  15.36],
 [264.01,  13.57],
 [200.71,  15.45],
 [249.37,  14.02],
 [151.5 ,  12.28],
 [151.82,  15.13],
 [181.92,  12.18],
 [228.65,  12.31],
 [223.78,  15.3 ],
 [266.63,  12.48],
 [273.68,  13.1 ],
 [220.61,  12.8 ],
 [284.99,  12.73]])

y = np.array([[1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [1.],
 [1.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [1.],
 [1.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [0.]])

# normalization

In [18]:
# before normalization
print('Temp: ', 'max: ', np.max(x[:,0]), 'min: ',np.min(x[:,0])) # col 1
print('Duration: ', 'max: ', np.max(x[:,1]), 'min: ',np.min(x[:,1])) # col 2

Temp:  max:  284.99 min:  151.32
Duration:  max:  15.45 min:  11.51


In [19]:
# normalization
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x)
x_new = norm_l(x)

In [21]:
# after normalization
print('Temp: ', 'max: ', np.max(x_new[:,0]), 'min: ',np.min(x_new[:,0])) # col 1
print('Duration: ', 'max: ', np.max(x_new[:,1]), 'min: ',np.min(x_new[:,1])) # col 2

Temp:  max:  1.659659 min:  -1.6853086
Duration:  max:  1.7897582 min:  -1.7021064


Tile/copy our data to increase the training set size and reduce the number of training epochs.

In [23]:
xt = np.tile(x_new, (1000, 1))
yt = np.tile(y, (1000, 1))

In [24]:
xt.shape

(200000, 2)

In [25]:
yt.shape

(200000, 1)

# model

In [64]:
tf.random.set_seed(1342)
model = Sequential([
    tf.keras.Input(shape=(2,)),
    Dense(units=5, activation='sigmoid', name='layer_1'),
    Dense(units=1, activation='sigmoid', name='layer_2')
])

In [65]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer_1 (Dense)                 │ (None, 5)              │            15 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21 (84.00 B)

 Trainable params: 21 (84.00 B)

 Non-trainable params: 0 (0.00 B)

# Parameters calculation

In [66]:
# Parameters=weight + biases
# Parameters = (Input Units × Output Units) + Output Units

# example

# | Layer    | Input Units | Output Units | Parameters   |
# | -------- | ----------- | ------------ | -------------|
# | Dense(8) | 3           | 8            | 3×8 + 8 = 32 |
# | Dense(5) | 8           | 5            | 8×5 + 5 = 45 |
# | Dense(2) | 5           | 2            | 5×2 + 2 = 12 |
# | Dense(1) | 2           | 1            | 2×1 + 1 = 3  |


# get weights and biases

In [67]:
w1, b1 = model.get_layer('layer_1').get_weights()
print('w1: ', w1, '\nshape: ', w1.shape)
print('b1: ', b1, '\nshape: ', b1.shape)
w2, b2 = model.get_layer('layer_2').get_weights()
print('w2: ', w2, '\nshape: ', w2.shape)
print('b2: ', b2, '\nshape: ', b2.shape)

w1:  [[ 0.88514924  0.04819459 -0.53139126  0.596558   -0.56652284]
 [ 0.8940575  -0.48042476  0.10958409  0.769156    0.21398866]] 
shape:  (2, 5)
b1:  [0. 0. 0. 0. 0.] 
shape:  (5,)
w2:  [[ 0.02644539]
 [ 0.7510884 ]
 [ 0.6832681 ]
 [ 0.07589746]
 [-0.94337606]] 
shape:  (5, 1)
b2:  [0.] 
shape:  (1,)


# train model

In [68]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
)

In [69]:
model.fit(xt, yt, epochs=10)

Epoch 1/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.2524
Epoch 2/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.1064
Epoch 3/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.0267
Epoch 4/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.0132
Epoch 5/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 0.0081
Epoch 6/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.0049
Epoch 7/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.0029
Epoch 8/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - loss: 0.0017
Epoch 9/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - loss: 9.1476e-04
Epoch 10/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 4.8797e-04


# updated weights and biases after fit

In [70]:
w1, b1 = model.get_layer('layer_1').get_weights()
print('w1: ', w1, '\nshape: ', w1.shape)
print('b1: ', b1, '\nshape: ', b1.shape)
w2, b2 = model.get_layer('layer_2').get_weights()
print('w2: ', w2, '\nshape: ', w2.shape)
print('b2: ', b2, '\nshape: ', b2.shape)

w1:  [[ -0.31948584   0.5992545   -8.445109    18.933447   -11.701638  ]
 [-10.441818   -17.562462   -16.750504    14.801568    -0.46347585]] 
shape:  (2, 5)
b1:  [-13.21925    14.466621    2.5005581   1.2841362 -13.059748 ] 
shape:  (5,)
w2:  [[-53.770947]
 [ 11.250407]
 [ 10.132253]
 [-57.128033]
 [-56.90694 ]] 
shape:  (5, 1)
b2:  [6.106789] 
shape:  (1,)


# prediction

In [71]:
new_data_point = np.array([
    [200,13.9],
    [200,17]])
new_data_pointn = norm_l(new_data_point)
pred = model.predict(new_data_pointn)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[9.999451e-01]
 [6.900531e-23]]


# convert to decision

In [75]:
yhat = np.zeros_like(pred)
# creates a new NumPy array yhat that: Has the same shape and data type as the predictions array and is filled with zeros.

for i in range(len(pred)):
  if pred[i] >= 0.5:
    yhat[i] = 1
  else:
    yhat[i] = 0
print('decisions:\n',yhat)

decisions:
 [[1.]
 [0.]]
