In [43]:
import numpy as np
import tensorflow as tf

# normlization

In [45]:
# before normalization
print('temp: ', 'max: ', np.max(x[:, 0]), 'min: ', np.min(x[:, 0]))
print('duration: ', 'max: ', np.max(x[:, 1]), 'min: ', np.min(x[:, 1]))

# normalization
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x)
xn = norm_l(x).numpy()

# after normalization
print('temp: ', 'max: ', np.max(xn[:, 0]), 'min: ', np.min(xn[:, 0]))
print('duration: ', 'max: ', np.max(xn[:, 1]), 'min: ', np.min(xn[:, 1]))

temp:  max:  284.99 min:  151.32
duration:  max:  15.45 min:  11.51
temp:  max:  1.659659 min:  -1.6853086
duration:  max:  1.7897582 min:  -1.7021064


# model

In [47]:
# activation function
def sigmoid(z):
  z = np.clip(z, -500, 500) # protect against overflow
  g = 1.0 / (1.0 + np.exp(-z))
  return g

# layer
def dense(AT, W, B):
  Z = np.matmul(AT, W) + B # matrix multiplication
  A_out = sigmoid(Z)
  return A_out

# model
def sequential(x, w1, b1, w2, b2):
  a1 = dense(x, w1, b1)
  print(a1)
  a2 = dense(a1, w2, b2)
  print(a2)
  return a2


# weights and biases initialization

In [49]:
w1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
w2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

# prediction

In [50]:
def predict(x, w1, b1, w2, b2):
  m = x.shape[0] # number of rows/samples
  p = np.zeros((m,1)) # zeros array to store predictions
  for i in range(m):
    p[i,0] = sequential(x[i], w1, b1, w2, b2)
  return (p)

In [51]:
x_test = np.array([[200, 13.9],
                   [200, 17]])
# normalize x_test
x_test_n = norm_l(x_test)

# make prediction
prediction = predict(x_test_n, w1_tmp, b1_tmp, w2_tmp, b2_tmp)

[3.36796188e-03 3.87488415e-06 3.61580204e-01]
[0.97157995]
[2.56094551e-03 7.14754494e-15 1.00000000e+00]
[3.28981203e-08]


/tmp/ipython-input-4245855571.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  p[i,0] = sequential(x[i], w1, b1, w2, b2)


In [52]:
print(prediction)

[[9.71579948e-01]
 [3.28981203e-08]]


# convert to decision

In [53]:
yhat = np.zeros_like(prediction) # zeros array to store decsion
for i in range(len(prediction)):
  if prediction[i] >= 0.5:
    yhat[i] = 1
  else:
    yhat[i] = 0
# print decisions
print(yhat)

[[1.]
 [0.]]
