In [1]:
import numpy as np
import tensorflow as tf

# model

In [9]:
# activation function
def relu(z):
  g = np.maximum(0, z)
  return g

# dense layer
def dense(AT, W, b):
  z = np.matmul(AT, W) + b
  A_out = relu(z)
  return A_out

# model
def sequential(x, w1, b1, w2, b2):
  a1 = dense(x, w1, b1)
  a2 = dense(a1, w2, b2)
  return a2

# prediction

In [18]:
w1_tmp = np.array([[0.5, 0.3, 0.1], [0.2, 0.4, 0.6]])
b1_tmp = np.array([0.1, 0.2, 0.3])
w2_tmp = np.array([[0.7], [0.8], [0.9]])
b2_tmp = np.array([0.5])

In [36]:
def predict(x, w1, b1, w2, b2):
  m = x.shape[0]
  p = np.zeros((m, 1))
  for i in range(m):
    p[i, 0] = sequential(x[i], w1, b1, w2, b2).item()
    print('\nSample: ', i, ' \nPredictions array:\n', p)
  return p

In [39]:
x_test = np.array([
    [150, -12],
    [-5, 10],
    [0, 0],
    [200, 30],
    [-100, -50],
    [50, -25],
    [-20, 5],
    [100, 0],
    [0, 100],
    [300, -100],
])
# normalize x_test
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x_test)
x_test_n = norm_l(x_test)

# make prediction
prediction = predict(x_test_n, w1_tmp, b1_tmp, w2_tmp, b2_tmp)


Sample:  0  
Predictions array:
 [[1.33346177]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Sample:  1  
Predictions array:
 [[1.33346177]
 [0.96872074]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Sample:  2  
Predictions array:
 [[1.33346177]
 [0.96872074]
 [0.80808159]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Sample:  3  
Predictions array:
 [[1.33346177]
 [0.96872074]
 [0.80808159]
 [2.48704807]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Sample:  4  
Predictions array:
 [[1.33346177]
 [0.96872074]
 [0.80808159]
 [2.48704807]
 [0.5       ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Sample:  5  
Predictions array:
 [[1.33346177]
 [0.96872074]
 [0.80808159]
 [2.48704807]
 [0.5       ]
 [0.52746645]
 [0.   

In [40]:
print(prediction)

[[1.33346177]
 [0.96872074]
 [0.80808159]
 [2.48704807]
 [0.5       ]
 [0.52746645]
 [0.83772426]
 [1.27945527]
 [2.7189989 ]
 [1.03640254]]
